heat_template_version: 2016-10-14

description: >
  OpenStack Nova Conductor service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NovaWorkers:
    default: 0
    description: Number of workers for Nova Conductor service.
    type: number
  MonitoringSubscriptionNovaConductor:
    default: 'overcloud-nova-conductor'
    type: string
  NovaSchedulerLoggingSource:
    type: json
    default:
      tag: openstack.nova.scheduler
      path: /var/log/nova/nova-scheduler.log
  UpgradeLevelNovaCompute:
    type: string
    description: Nova Compute upgrade level
    default: auto

conditions:
  nova_workers_zero: {equals : [{get_param: NovaWorkers}, 0]}

resources:
  NovaBase:
    type: ./nova-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Nova Conductor service.
    value:
      service_name: nova_conductor
      monitoring_subscription: {get_param: MonitoringSubscriptionNovaConductor}
      logging_source: {get_param: NovaSchedulerLoggingSource}
      logging_groups:
        - nova
      config_settings:
        map_merge:
        - get_attr: [NovaBase, role_data, config_settings]
        -
          if:
          - nova_workers_zero
          - {}
          - nova::conductor::workers: {get_param: NovaWorkers}
      step_config: |
        include tripleo::profile::base::nova::conductor
      upgrade_tasks:
        - name: Stop nova_conductor service
          tags: step2
          service: name=openstack-nova-conductor state=stopped
        # If not already set by puppet (e.g a pre-ocata version), set the
        # upgrade_level for compute to "auto"
        - name: Set compute upgrade level to auto
          tags: step3
          command:
            str_replace:
              template: "crudini  --set /etc/nova/nova.conf upgrade_levels compute LEVEL"
              params:
                LEVEL: {get_param: UpgradeLevelNovaCompute}
        #- name: Sync nova_conductor DB
        #  tags: step5
        #  command: nova-manage db sync
        #- name: DB online migrations
        #  tags: step5
        #  command: nova-manage db online_data_migrations
        - name: Start nova_conductor service
          tags: step6
          service: name=openstack-nova-conductor state=started
