heat_template_version: 2016-10-14

description: >
  Pacemaker service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MonitoringSubscriptionPacemaker:
    default: 'overcloud-pacemaker'
    type: string
  CorosyncIPv6:
    default: false
    description: Enable IPv6 in Corosync
    type: boolean
  EnableFencing:
    default: false
    description: Whether to enable fencing in Pacemaker or not.
    type: boolean
  PcsdPassword:
    type: string
    description: The password for the 'pcsd' user for pacemaker.
    hidden: true
    default: ''
  FencingConfig:
    default: {}
    description: |
      Pacemaker fencing configuration. The JSON should have
      the following structure:
        {
          "devices": [
            {
              "agent": "AGENT_NAME",
              "host_mac": "HOST_MAC_ADDRESS",
              "params": {"PARAM_NAME": "PARAM_VALUE"}
            }
          ]
        }
      For instance:
        {
          "devices": [
            {
              "agent": "fence_xvm",
              "host_mac": "52:54:00:aa:bb:cc",
              "params": {
                "multicast_address": "225.0.0.12",
                "port": "baremetal_0",
                "manage_fw": true,
                "manage_key_file": true,
                "key_file": "/etc/fence_xvm.key",
                "key_file_password": "abcdef"
              }
            }
          ]
        }
    type: json
  PacemakerLoggingSource:
    type: json
    default:
      tag: system.pacemaker
      path: /var/log/pacemaker.log,/var/log/cluster/corosync.log
      format: >-
        /^(?<time>[^ ]*\s*[^ ]* [^ ]*)
        \[(?<pid>[^ ]*)\]
        (?<host>[^ ]*)
        (?<message>.*)$/

  #Parameters defined for upgrades.
  UpgradeLevelNovaCompute:
    type: string
    description: Nova Compute upgrade level
    default: ''
  MySqlMajorUpgrade:
    type: string
    description: Can be auto,yes,no and influences if the major upgrade should do or detect an automatic mysql upgrade
    constraints:
    - allowed_values: ['auto', 'yes', 'no']
    default: 'auto'
  IgnoreCephUpgradeWarnings:
    type: boolean
    default: false
    description: If enabled, Ceph upgrade will be forced even though cluster or PGs status is not clean
  KeepSaharaServicesOnUpgrade:
    type: boolean
    default: true
    description: Whether to keep Sahara services when upgrading controller nodes from mitaka to newton


outputs:
  role_data:
    description: Role data for the Pacemaker role.
    value:
      service_name: pacemaker
      monitoring_subscription: {get_param: MonitoringSubscriptionPacemaker}
      logging_groups:
        - haclient
      logging_source: {get_param: PacemakerLoggingSource}
      config_settings:
        pacemaker::corosync::cluster_name: 'tripleo_cluster'
        pacemaker::corosync::manage_fw: false
        pacemaker::resource_defaults::defaults:
          resource-stickiness: { value: INFINITY }
        corosync_token_timeout: 10000
        tripleo.pacemaker.firewall_rules:
          '130 pacemaker tcp':
            proto: 'tcp'
            dport:
              - 2224
              - 3121
              - 21064
          '131 pacemaker udp':
            proto: 'udp'
            dport: 5405
        corosync_ipv6: {get_param: CorosyncIPv6}
        tripleo::fencing::config: {get_param: FencingConfig}
        enable_fencing: {get_param: EnableFencing}
        hacluster_pwd:
          yaql:
            expression: $.data.passwords.where($ != '').first()
            data:
              passwords:
                - {get_param: PcsdPassword}
                - {get_param: [DefaultPasswords, pcsd_password]}
      step_config: |
        include ::tripleo::profile::base::pacemaker
      upgrade_tasks:
        - name: Run pacemaker upgrade step 1 (Prepare for upgrade)
          tags: step1
          become: true
          shell: |
            #!/bin/bash
            set -eu
            mariadb_do_major_upgrade='{get_param: MySqlMajorUpgrade}'
            upgrade_level_nova_compute='{get_param: UpgradeLevelNovaCompute}'
            source /root/tripleo-heat-templates/extraconfig/tasks/pacemaker_common_functions.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_check.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_pacemaker_migrations.sh
            . /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_controller_pacemaker_1.sh
          ignore_errors: yes

        - name: Run pacemaker upgrade step 2  (Stopping services)
          tags: step2
          become: true
          shell: |
            #!/bin/bash
            set -eu
            mariadb_do_major_upgrade='{get_param: MySqlMajorUpgrade}'
            upgrade_level_nova_compute='{get_param: UpgradeLevelNovaCompute}'
            backup_flags="--defaults-extra-file=/root/.my.cnf -u root --flush-privileges --all-databases --single-transaction"
            MYSQL_BACKUP_DIR=/var/tmp/mysql_upgrade_osp
            MYSQL_TEMP_UPGRADE_BACKUP_DIR=/var/lib/mysql-temp-upgrade-backup
            # Spare disk ratio for extra safety
            MYSQL_BACKUP_SIZE_RATIO=1.2
            source /root/tripleo-heat-templates/extraconfig/tasks/pacemaker_common_functions.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_check.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_pacemaker_migrations.sh
            . /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_controller_pacemaker_2_1.sh
          ignore_errors: yes

        - name: Run pacemaker upgrade step 3  (Upgrading services)
          tags: step3
          become: true
          shell: |
            #!/bin/bash
            set -eu
            mariadb_do_major_upgrade='{get_param: MySqlMajorUpgrade}'
            upgrade_level_nova_compute='{get_param: UpgradeLevelNovaCompute}'
            backup_flags="--defaults-extra-file=/root/.my.cnf -u root --flush-privileges --all-databases --single-transaction"
            MYSQL_BACKUP_DIR=/var/tmp/mysql_upgrade_osp
            MYSQL_TEMP_UPGRADE_BACKUP_DIR=/var/lib/mysql-temp-upgrade-backup
            # Spare disk ratio for extra safety
            MYSQL_BACKUP_SIZE_RATIO=1.2
            source /root/tripleo-heat-templates/extraconfig/tasks/pacemaker_common_functions.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_check.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_pacemaker_migrations.sh
            . /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_controller_pacemaker_2_2.sh
          ignore_errors: yes

        - name: Run pacemaker upgrade step 4 (starting services)
          tags: step4
          become: true
          shell: |
            #!/bin/bash
            set -eu
            source /root/tripleo-heat-templates/extraconfig/tasks/pacemaker_common_functions.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_pacemaker_migrations.sh
            . /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_controller_pacemaker_3_1.sh
          ignore_errors: yes

        - name: Run pacemaker upgrade step 5 (sync db)
          tags: step5
          become: true
          shell: |
            #!/bin/bash
            source /root/tripleo-heat-templates/extraconfig/tasks/pacemaker_common_functions.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_pacemaker_migrations.sh
            . /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_controller_pacemaker_3_2.sh
          ignore_errors: yes

        - name: Run pacemaker upgrade step 6
          tags: step5
          become: true
          shell: |
            #!/bin/bash
            source /root/tripleo-heat-templates/extraconfig/tasks/pacemaker_common_functions.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_pacemaker_migrations.sh
            . /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_controller_pacemaker_4.sh          
          ignore_errors: yes

        - name: Run pacemaker upgrade step 7
          tags: step5
          become: true
          shell: |
            #!/bin/bash
            source /root/tripleo-heat-templates/extraconfig/tasks/pacemaker_common_functions.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_pacemaker_migrations.sh
            . /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_controller_pacemaker_5.sh          
          ignore_errors: yes

        - name: Run pacemaker upgrade step 8
          tags: step5
          become: true
          shell: |
            #!/bin/bash
            keep_sahara_services_on_upgrade='{get_param: KeepSaharaServicesOnUpgrade}'
            source /root/tripleo-heat-templates/extraconfig/tasks/pacemaker_common_functions.sh
            source /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_pacemaker_migrations.sh
            . /root/tripleo-heat-templates/extraconfig/tasks/major_upgrade_controller_pacemaker_6.sh          
          ignore_errors: yes