heat_template_version: 2016-04-08

description: >
  OpenStack Swift Storage service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  SwiftMountCheck:
    default: false
    description: Value of mount_check in Swift account/container/object -server.conf
    type: boolean
  SwiftRawDisks:
    default: {}
    description: 'A hash of additional raw devices to use as Swift backend (eg. {sdb: {}})'
    type: json
  MonitoringSubscriptionSwiftStorage:
    default: 'overcloud-swift-storage'
    type: string

  # DEPRECATED options for compatibility with overcloud.yaml
  # This should be removed and manipulation of the ControllerServices list
  # used instead, but we need client support for that first
  ControllerEnableSwiftStorage:
    default: true
    description: Whether to enable Swift Storage on the Controller
    type: boolean

parameter_groups:
- label: deprecated
  description: Do not use deprecated params, they will be removed.
  parameters:
  - ControllerEnableSwiftStorage

resources:
  SwiftBase:
    type: ./swift-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Swift Proxy role.
    value:
      service_name: swift_storage
      monitoring_subscription: {get_param: MonitoringSubscriptionSwiftStorage}
      config_settings:
        map_merge:
          - get_attr: [SwiftBase, role_data, config_settings]
          - swift::storage::all::mount_check: {get_param: SwiftMountCheck}
            tripleo::profile::base::swift::storage::enable_swift_storage: {get_param: ControllerEnableSwiftStorage}
            tripleo.swift_storage.firewall_rules:
              '123 swift storage':
                dport:
                  - 873
                  - 6000
                  - 6001
                  - 6002
            swift::storage::all::incoming_chmod: 'Du=rwx,g=rx,o=rx,Fu=rw,g=r,o=r'
            swift::storage::all::outgoing_chmod: 'Du=rwx,g=rx,o=rx,Fu=rw,g=r,o=r'
            swift::storage::all::object_pipeline:
              - healthcheck
              - recon
              - object-server
            swift::storage::all::container_pipeline:
              - healthcheck
              - container-server
            swift::storage::all::account_pipeline:
              - healthcheck
              - account-server
            swift::storage::disks::args: {get_param: SwiftRawDisks}
            swift::storage::all::storage_local_net_ip: {get_param: [ServiceNetMap, SwiftStorageNetwork]}
      step_config: |
        include ::tripleo::profile::base::swift::storage
      upgrade_tasks:
        - name: Stop swift object replicator service
          tags: step2
          service: name=openstack-swift-object-replicator state=stopped
        - name: Stop swift object auditor service
          tags: step2
          service: name=openstack-swift-object-auditor state=stopped
        - name: Stop swift object updater service
          tags: step2
          service: name=openstack-swift-object-updater state=stopped

        - name: Stop swift container replicator service
          tags: step2
          service: name=openstack-swift-container-replicator state=stopped
        - name: Stop swift container auditor service
          tags: step2
          service: name=openstack-swift-container-auditor state=stopped
        - name: Stop swift container updater service
          tags: step2
          service: name=openstack-swift-container-updater state=stopped
        - name: Stop swift container service
          tags: step2
          service: name=openstack-swift-container state=stopped

        - name: Stop swift account replicator service
          tags: step2
          service: name=openstack-swift-account-replicator state=stopped
        - name: Stop swift account auditor service
          tags: step2
          service: name=openstack-swift-account-auditor state=stopped
        - name: Stop swift account reaper service
          tags: step2
          service: name=openstack-swift-account-reaper state=stopped
        - name: Stop swift account service
          tags: step2
          service: name=openstack-swift-account state=stopped


        - name: Start swift object replicator service
          tags: step6
          service: name=openstack-swift-object-replicator state=started
        - name: Start swift object auditor service
          tags: step6
          service: name=openstack-swift-object-auditor state=started
        - name: Start swift object updater service
          tags: step6
          service: name=openstack-swift-object-updater state=started

        - name: Start swift container replicator service
          tags: step6
          service: name=openstack-swift-container-replicator state=started
        - name: Start swift container auditor service
          tags: step6
          service: name=openstack-swift-container-auditor state=started
        - name: Start swift container updater service
          tags: step6
          service: name=openstack-swift-container-updater state=started
        - name: Start swift container service
          tags: step6
          service: name=openstack-swift-container state=started

        - name: Start swift account replicator service
          tags: step6
          service: name=openstack-swift-account-replicator state=started
        - name: Start swift account auditor service
          tags: step6
          service: name=openstack-swift-account-auditor state=started
        - name: Start swift account reaper service
          tags: step6
          service: name=openstack-swift-account-reaper state=started
        - name: Start swift account service
          tags: step6
          service: name=openstack-swift-account state=started

